### ISSUE TITLE
Performance profiling.

### ISSUE THREAD

**Issue by NoraCodes** [rtlsdrblog/kerberossdr#2]
So, first off, KerberosSDR and the software here are awesome. Thank you so much for building them. But _dang_ is this stuff slow!

I spent a few hours working on optimizations for performance today and didn't really get much better than a 5-8% reduction in processing time. I'd really like to do better but my normal profiling methods (`cProfile` and `perf`) aren't working for me; I can't get `cProfile` to emit anything of use, and running the GUI under `perf` leads to a blank window:

```
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x6600020
```

Other than the numpy array ingestion, do you know what uses the most CPU time? Would it be possible to modularize the Python software so it's easier to profile?

**Comment by rtlsdrblog** [comment]
Are you running the latest code / img file? I made a few enhancements to the speed during the latest push. Also what platform are you running on, and what are you doing with the program (DOA, or PR?). The program shouldn't be annoyingly slow even on a Pi3. To get an idea, on the Pi3 we're getting about a 1Hz update rate on both DoA and PR, which should be sufficient in most cases. Of course if you use a Tinkerboard, or an x86 machine it will be much faster.

One thing to take care of is to remember to turn OFF plotting that you are not using. For example, if you're finished syncing, remember to turn off the syncing graphs. Leaving them on results in the sync correlation code running continuously, which is inherently CPU intensive.

If you're on a fast machine you can experiment with the time.sleep in the signal processing Python code. Reducing the sleep lets the program update faster, but increases CPU usage. If CPU usage is too high it might starve the rtl_daq, sync and gate C processes which can result in a loss of sync at random times.

Also if you installed it yourself on your own machine, try to check what LAPACK and BLAS libraries your Python numpy and scipy environment is using "sudo update-alternatives --all". It should be using an optimized library like libatlas or OpenBLAS. OpenBLAS seems to open more threads than libatlas though, and causes much higher CPU usage on slow machines like the Pi3.

Another thing you could experiment with if increased speed is really required is reducing the block size. At the moment this is hard coded in due to a weird bug I encountered when trying to make it configurable at runtime, but you can edit the rtl_daq.c, sync.c and gate.c files, and halve the BUFF_LEN and BUFFER_SIZE parameters, then recompile. Then edit the BUFF_SIZE parameter in the run.sh code to 128. Halving the block size may result in less accurate results and lower resolution PR, but much faster processing.

I'm not sure why profiling isn't working for you though, I did have cProfile running at one point in the testing phase, but haven't run it recently. 

Most of the processing occurs in Tamas' pyARGUS and pyAPRIL libraries, but I think they're already pretty well optimized. There might be gains to be had by rewriting them in C, but that could also make it slower as numpy is supposed to be pretty well optimized.

**Comment by NoraCodes** [comment]
Actually, after a lot of kind of futile futzing about trying to find what was using CPU, it turns out the main blocker is `time.sleep(0.25)` on line 159 of `hydra_signal_processor`. Reducing that directly affects the processing speed, down from about 280 to 63 ms on my desktop.

Is there a reason I should keep that in?

**Comment by rtlsdrblog** [comment]
Yep in some cases you might want to have the program sleep, see the previous reply:

"If you're on a fast machine you can experiment with the time.sleep in the signal processing Python code. Reducing the sleep lets the program update faster, but increases CPU usage. If CPU usage is too high it might starve the rtl_daq, sync and gate C processes which can result in a loss of sync at random times."

So if you remove the sleep, be sure to test the long term stability of the sync (if required). I note that on slow machines the faster update rate might also starve the GUI.
